<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>v4.8</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toolbox.Core.csproj" />
  </ItemGroup>

</Project>
